<a href="https://colab.research.google.com/github/zuzanna-w17/ML-course/blob/main/regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear regression

In [1]:
! pip install scikit-learn

In [2]:
! pip install --upgrade scikit-learn

In [3]:
# libraries
import numpy as np

In [8]:
# data
X1 = np.array([1, 2, 3, 4, 5, 6])
Y1 = np.array([3000, 3250, 3500, 3750, 4000, 4250])

m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y1}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [9]:
# change format
X1 = X1.reshape(m, 1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [10]:
# constant term
bias = np.ones((m, 1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [11]:
# add
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


## Normal equation: W = (X^T X)^(-1) (X^T Y), where W is estimates

In [12]:
# X^T X - multiplication of matrices
np.dot(X.T, X)

array([[ 6., 21.],
       [21., 91.]])

In [14]:
# inverted matrix
L = np.linalg.inv(np.dot(X.T, X))
L

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [17]:
P = np.dot(X.T, Y1)
P

array([21750., 80500.])

In [18]:
# final
np.dot(L, P)

array([2750.,  250.])

In [25]:
# on scikit-learn
from sklearn.linear_model import LinearRegression

regression = LinearRegression() # class instance
regression.fit(X1, Y1)

print(regression.intercept_)
print(regression.coef_[0])

2750.0
250.0
